### PR TITLE
Fixes typo in warning message

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by 36000** [comment]
LGTM! I don't have write access so you will have to merge.

**Comment by arokem** [comment]
I just added you as a member to the tractometry org. Do you now have merge access?

**Comment by 36000** [comment]
It says: "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests"

**Comment by arokem** [comment]
How about now?

**Comment by 36000** [comment]
Yes!

**Pull request merged**
