### PR TITLE
Too many t's in https

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
Looks like we are running into something like this: https://github.com/NVIDIA/thrust/issues/1948

**Comment by 36000** [comment]
I opened a PR here to see if this fixes it: https://github.com/dipy/GPUStreamlines/pull/20

**Comment by arokem** [comment]
Thanks! I just merged that and will retrigger the CI here.

**Comment by 36000** [comment]
OK, we can undo my last commit then

**Comment by arokem** [comment]
I just noticed something that seems a bit fishy, which is that we are always building the docker images from the main branch on GitHub: https://github.com/tractometry/pyAFQ/blob/main/gpu_docker/Dockerfile#L25, which means that the CI builds are not really testing the installation of the branch on which they get built, which maybe is a problem?

**Comment by 36000** [comment]
No, we use this code, which should work on branches but only if you are on this repo, which is why we didn't have it run on PRs before:
```
# clone pyAFQ GPUStreamlines
RUN git clone https://github.com/tractometry/pyAFQ.git /opt/pyAFQ
RUN cd /opt/pyAFQ && git reset --hard ${COMMIT}
RUN cd /opt/pyAFQ && pip install -e .
RUN /opt/pyAFQ/bin/pyAFQ download
```

maybe there is a way to get the repo name and branch too instead of using COMMIT?

**Comment by arokem** [comment]
I think you also need to know from which remote to fetch it, so it might get complicated.

**Comment by arokem** [comment]
I'll go ahead and merge this. I think that it fixes what it's supposed to fix and we can fix the broken pypi CI on a separate PR.

**Pull request merged**
